##What percentage of total company revenue is generated by the top 10 products?

WITH product_sales AS(
	SELECT Category,
    Product_ID,
    Product_Name,
    SUM(Revenue) AS total_revenue
    FROM transactions
    GROUP BY Category,
    Product_ID,
    Product_Name),
    total_products AS(
    SELECT*
    FROM product_sales
    ORDER BY total_revenue DESC
    LIMIT 10)
    SELECT 
    SUM(total_revenue) AS revenue_by_top_10,
    ROUND(
    SUM(total_revenue)/(SELECT SUM(Revenue) FROM transactions)*100,2
    ) AS pct_of_revenue_by_top_10
    FROM total_products;
    